coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%

ignore:
  - "src/main.rs"
  - "src/bin/**/*"
  - "tools/**/*"
  - "tests/**/*"
  - "src/**/*_test.rs"
  - "src/admin/pages/**/*"
  - "src/admin/sse.rs"
